<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
 <testsuite name="User chat load test" timestamp="2016-12-17T20:10:55" hostname="localhost" time="40.009" errors="0" tests="1" skipped="0" disabled="0" failures="2">
  <testcase classname="User chat load test" name="should connect and send 200  user messages within 2000ms" time="40.008">
   <failure type="exception" message="Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL."><![CDATA[Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    at Timeout._onTimeout (/home/birkirfreyr/Desktop/3vikna/dt1/reference-tictactoe/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1973:23)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)]]>
   </failure>
   <failure type="exception" message="Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL."><![CDATA[Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    at Timeout._onTimeout (/home/birkirfreyr/Desktop/3vikna/dt1/reference-tictactoe/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1973:23)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)]]>
   </failure>
  </testcase>
 </testsuite>
</testsuites>